version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=MySecureRootPassword123!
      - DATABASE_NAME=ti_trading_performance
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MySecureRootPassword123!
      MYSQL_DATABASE: ti_trading_performance
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_design.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  scheduler:
    build: .
    command: python src/scheduler.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=MySecureRootPassword123!
      - DATABASE_NAME=ti_trading_performance
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
